# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16)),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=16)),
                ('ciudad', models.CharField(max_length=30)),
                ('cp', models.IntegerField()),
                ('kilometros', models.IntegerField()),
                ('rfc', models.CharField(max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16)),
                ('departamento', models.CharField(max_length=16)),
                ('telefono', models.CharField(max_length=16)),
                ('extension', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.IntegerField()),
                ('horas_extra', models.IntegerField(blank=True, null=True)),
                ('horas_viaje', models.IntegerField()),
                ('kilometros', models.IntegerField()),
                ('hotel', models.IntegerField(blank=True, null=True)),
                ('manuales', models.IntegerField(blank=True, null=True)),
                ('traslados', models.IntegerField(blank=True, null=True)),
                ('aviones', models.IntegerField(blank=True, null=True)),
                ('sobre_equipaje', models.IntegerField(blank=True, null=True)),
                ('renta_auto', models.IntegerField(blank=True, null=True)),
                ('papeleria', models.IntegerField(blank=True, null=True)),
                ('importe', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('SA', models.IntegerField()),
                ('tipo_cambio', models.DecimalField(decimal_places=2, max_digits=2)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Contactos')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingenieros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=4)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('horas', models.IntegerField()),
                ('horas_extra', models.IntegerField()),
                ('horas_viaje', models.IntegerField()),
                ('kilometros', models.IntegerField()),
                ('hotel', models.IntegerField()),
                ('manuales', models.IntegerField()),
                ('traslados', models.IntegerField()),
                ('avion', models.IntegerField()),
                ('sobre_equipaje', models.IntegerField()),
                ('renta_auto', models.IntegerField()),
                ('papeleria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(blank=True, max_length=13, null=True)),
                ('fabricante', models.CharField(max_length=15)),
                ('no_serie', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
                ('rango_x', models.IntegerField()),
                ('rango_y', models.IntegerField()),
                ('rango_z', models.IntegerField()),
                ('mppl', models.IntegerField()),
                ('mppe', models.IntegerField()),
                ('probe_type', models.CharField(max_length=10)),
                ('probe_head', models.CharField(max_length=16)),
                ('probe_serial', models.CharField(max_length=15)),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('version_software', models.CharField(max_length=15)),
                ('version_firmware', models.CharField(max_length=15)),
                ('controlador', models.CharField(max_length=10)),
                ('accesorios', models.CharField(blank=True, max_length=15, null=True)),
                ('driver_software', models.CharField(max_length=15)),
                ('modelo_computadora', models.CharField(max_length=10)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('diametro_stylus', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes_de_servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('pagada', models.IntegerField()),
                ('observaciones', models.CharField(max_length=255)),
                ('viaticos', models.IntegerField()),
                ('orden_compra', models.CharField(max_length=15)),
                ('orden_compra_interna', models.IntegerField()),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('viaticos_pagados', models.IntegerField(null=True)),
                ('cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Cotizacion')),
                ('ingeniero', models.ManyToManyField(to='sistema.Ingenieros')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='orden_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Ordenes_de_servicio'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='maquinas',
            field=models.ManyToManyField(to='sistema.Maquinas'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='servicio',
            field=models.ManyToManyField(to='sistema.Servicios'),
        ),
    ]
