# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinas',
            name='cliente',
        ),
        migrations.AddField(
            model_name='maquinas',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Contactos'),
        ),
    ]
