# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20160108_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingenieros',
            name='numero',
        ),
    ]
