# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_ingenieros_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingenieros',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
    ]
