# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20160109_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='horas',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
