# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20160109_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='contacto_a_facturar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Contactos'),
        ),
        migrations.AddField(
            model_name='ingenieros',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
