# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20160115_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaprecios',
            name='horas_viaje',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
