# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20160118_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.16, max_digits=5),
        ),
    ]
