# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20160118_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='horas_viaje',
        ),
    ]
