# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_remove_cotizacion_horas_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprecios',
            name='horas_viaje',
            field=models.IntegerField(null=True),
        ),
    ]
