# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_listaprecios_horas_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_servicio',
            name='orden_compra_interna',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
