# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_auto_20160119_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='terminos_pago',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordenes_de_servicio',
            name='fecha_servicio',
            field=models.DateField(null=True),
        ),
    ]
