# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_auto_20160120_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes_de_servicio',
            name='mail_enviado',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
    ]
