# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_auto_20160122_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_servicio',
            name='mail_enviado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
