# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_auto_20160126_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminos_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminos', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='factura',
            name='terminos_pago',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='clientes',
            name='terminos_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Terminos_pago'),
        ),
    ]
