# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_auto_20160126_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
